### ISSUE TITLE
Trouble intstalling

### ISSUE THREAD

**Issue by songproducer** [marigold-dev/training-nft-1#9]
taq --version
v0.24.2

taq install @taqueria/plugin-ligo@next

```
@taqueria/plugin-core encountered an unexpected problem. Use --debug to learn more.
```

taq install @taqueria/plugin-ligo@next --debug

```
E_PARSE_UNKNOWN: There was a problem trying to parse the plugin request arguments
    at /Users/leotreasure/training-nft-1/training/node_modules/@taqueria/node-sdk/index.js:137:39
    at call (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:139:31)
    at Transformation.MapRejTransformation$rejected (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:1491:39)
    at Transformation.transformationHandler [as rejected] (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:743:21)
    at rejected (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:615:29)
    at Interpreter.Reject$interpret [as _interpret] (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:528:5)
    at drain (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:682:27)
    at settle (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:608:17)
    at Interpreter.Transformer$interpret [as _interpret] (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:695:5)
    at promise$computation (/Users/leotreasure/training-nft-1/training/node_modules/fluture/index.cjs:1721:9) {
  context: [
    '/Users/leotreasure/.nvm/versions/node/v18.12.1/bin/node',
    '/Users/leotreasure/training-nft-1/training/node_modules/@taqueria/plugin-core/index.js',
    '--taqRun',
    'pluginInfo',
    '--i18n',
    '{}',
    '--config',
    '{"language":"en","contractsDir":"contracts","artifactsDir":"artifacts","network":{"ghostnet":{"label":"ghostnet","rpcUrl":"https://ghostnet.ecadinfra.com","protocol":"PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg"}},"sandbox":{"local":{"label":"Local Tezos Sandbox","rpcUrl":"http://localhost:20000","protocol":"PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg"}},"environment":{"default":"development","development":{"networks":[],"sandboxes":["local"]},"testing":{"networks":["ghostnet"],"sandboxes":[]}},"accounts":{"bob":"3_000_000_000","alice":"3_000_000_000","john":"3_000_000_000","jane":"3_000_000_000","joe":"3_000_000_000"},"plugins":[{"name":"@taqueria/plugin-core","type":"npm"}],"projectDir":"/Users/leotreasure/training-nft-1/training","configFile":"/Users/leotreasure/training-nft-1/training/.taq/config.json","hash":"55d25421790b7a58915a3f248d7111ef07b4f9f66648aa8cf80a060f1cdfe1cd"}',
    '--envVars',
    '{}',
    '--projectDir',
    '/Users/leotreasure/training-nft-1/training',
    '--maxConcurrency',
    '10',
    '--debug',
    'true',
    '--logPluginRequests',
    'false',
    '--fromVsCode',
    'false',
    '--help',
    'false',
    '--yes',
    'false',
    '--setBuild',
    'dd46883',
    '--setVersion',
    'v0.24.2',
    '--lock',
    './deno-lock.json',
    '--d',
    'true',
    '--p',
    './'
  ],
  kind: 'E_PARSE_UNKNOWN',
  previous: {
    kind: 'E_PARSE',
    msg: 'RequestArgs is invalid:\n' +
      'disableState: Required\n' +
      'version: Required\n' +
      'build: Required\n',
    context: undefined,
    previous: ZodError: [
      {
        "code": "invalid_type",
        "expected": "boolean",
        "received": "undefined",
        "path": [
          "disableState"
        ],
        "message": "Required"
      },
      {
        "code": "invalid_type",
        "expected": "boolean",
        "received": "undefined",
        "path": [
          "version"
        ],
        "message": "Required"
      },
      {
        "code": "invalid_type",
        "expected": "boolean",
        "received": "undefined",
        "path": [
          "build"
        ],
        "message": "Required"
      }
    ]
        at get error [as error] (/Users/leotreasure/training-nft-1/training/node_modules/zod/lib/types.js:43:31)
        at ZodObject.parse (/Users/leotreasure/training-nft-1/training/node_modules/zod/lib/types.js:141:22)
        at Object.from32 (/Users/leotreasure/training-nft-1/training/node_modules/@taqueria/protocol/index.js:2035:30)
        at parseArgs (/Users/leotreasure/training-nft-1/training/node_modules/@taqueria/node-sdk/index.js:256:49)
        at Object.create (/Users/leotreasure/training-nft-1/training/node_modules/@taqueria/node-sdk/index.js:601:12)
        at Object.<anonymous> (/Users/leotreasure/training-nft-1/training/node_modules/@taqueria/plugin-core/index.js:56:25)
        at Module._compile (node:internal/modules/cjs/loader:1159:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
        at Module.load (node:internal/modules/cjs/loader:1037:32)
        at Module._load (node:internal/modules/cjs/loader:878:12) {
      issues: [Array],
      addIssue: [Function (anonymous)],
      addIssues: [Function (anonymous)],
      errors: [Array]
    }
  }
}

taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

{
  kind: "E_INVALID_PLUGIN_RESPONSE",
  msg: "The @taqueria/plugin-core plugin experienced an error when getting information about the @taqueria/p...",
  context: undefined,
  previous: {
    kind: "E_PARSE",
    msg: "The schema returned from the plugin is invalid",
    context: undefined,
    previous: ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at handleResult (https://deno.land/x/zod@v3.14.4/types.ts:30:23)
    at ZodEffects.safeParse (https://deno.land/x/zod@v3.14.4/types.ts:134:16)
    at ZodEffects.parse (https://deno.land/x/zod@v3.14.4/types.ts:112:29)
    at Module.internalOf (file:///Users/runner/work/taqueria/taqueria/taqueria-protocol/Base.ts:28:43)
    at file:///Users/runner/work/taqueria/taqueria/plugins.ts:164:178
    at call (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:501:29)
    at Transformation.ChainTransformation$resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1175:62)
    at Transformation.transformationHandler [as resolved] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1105:19)
    at resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:984:27)
    at Interpreter.Resolve$interpret [as _interpret] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:903:3)
  }
}
{
  kind: "E_PARSE",
  msg: "The schema returned from the plugin is invalid",
  context: undefined,
  previous: ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at handleResult (https://deno.land/x/zod@v3.14.4/types.ts:30:23)
    at ZodEffects.safeParse (https://deno.land/x/zod@v3.14.4/types.ts:134:16)
    at ZodEffects.parse (https://deno.land/x/zod@v3.14.4/types.ts:112:29)
    at Module.internalOf (file:///Users/runner/work/taqueria/taqueria/taqueria-protocol/Base.ts:28:43)
    at file:///Users/runner/work/taqueria/taqueria/plugins.ts:164:178
    at call (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:501:29)
    at Transformation.ChainTransformation$resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1175:62)
    at Transformation.transformationHandler [as resolved] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1105:19)
    at resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:984:27)
    at Interpreter.Resolve$interpret [as _interpret] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:903:3)
}
ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at handleResult (https://deno.land/x/zod@v3.14.4/types.ts:30:23)
    at ZodEffects.safeParse (https://deno.land/x/zod@v3.14.4/types.ts:134:16)
    at ZodEffects.parse (https://deno.land/x/zod@v3.14.4/types.ts:112:29)
    at Module.internalOf (file:///Users/runner/work/taqueria/taqueria/taqueria-protocol/Base.ts:28:43)
    at file:///Users/runner/work/taqueria/taqueria/plugins.ts:164:178
    at call (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:501:29)
    at Transformation.ChainTransformation$resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1175:62)
    at Transformation.transformationHandler [as resolved] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:1105:19)
    at resolved (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:984:27)
    at Interpreter.Resolve$interpret [as _interpret] (https://cdn.jsdelivr.net/gh/fluture-js/Fluture@14.0.0/dist/module.js:903:3)

```

**Comment by songproducer** [comment]
updating taq to latest beta v0.28.4 fixed it.

**Comment by zamrokk** [comment]
try to install taqueria v0.28.5  instead =>  https://github.com/ecadlabs/taqueria/releases/tag/v0.28.5-rc
